### ISSUE TITLE
grid_description.yaml file not found 

### ISSUE THREAD

**Issue by ymkuan** [vosjo/speedyfit#9]
I have grid_description.yaml in the corresponding directory, but after executing ''speedyfit checkgrids'',  python told me that there is no grid_description.yaml file

’‘‘
Checking which atmosphere models are available...
Checking for models in </home/ymk/miniconda3/sed_models to extracted atmosphere models>
grid_description.yaml file not found or no models included in the description file.
Please add a grid_description.yaml file in the SPEEDYFIT_MODELS directory.
’’’

My directory contains the following files:
blackbody_discint.fits
grid_description.yaml
iblackbody_discint_lawfitzpatrick2004_Rv3.10.fits
ikurucz93_z0.0_k2odfnew_sed_lawfitzpatrick2004_Rv3.10.fits
iMunari2005_extended_lawfitzpatrick2004_Rv3.10.fits
iTMAP2012_sdOB_extended_lawfitzpatrick2004_Rv3.10.fits
kurucz93_z0.0_k2odfnew_sed.fits
Munari2005_extended.fits
TMAP2012_sdOB_extended.fits

The grid_description.yaml is just in directory. I do not know how to solve it. Please.

Thanks very much.

**Comment by vosjo** [comment]
there is indeed an issue when reading the model fits files from a path containing spaces. This is fixed in the last release. 
However, the error message that gave is not the same as the one you got. So I don't think this is your problem. 

Please update speedyfit, and get back to me if it still doesn't work. The error output is more extended in the new version.

**Comment by ymkuan** [comment]
Hi sir:

very very thanks ~.  I reinstalled the speedyfit, and installed model fits in a different path. Finally I got the correct output!

yeah~

ymkuan

**Comment by vosjo** [comment]
Glad it works now.
